[theme]
base = "dark"
backgroundColor = "#212121"
secondaryBackgroundColor = "#171717"
textColor = "#ececec"
primaryColor = "#19c37d"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
