"""
knowledge_graph/graph/neo4j_exporter.py
─────────────────────────────────────────────────────────────────────────────
Exports the MOSDAC Knowledge Graph as Neo4j Cypher statements.

This is OPTIONAL — only needed if you want to load the KG into a running
Neo4j instance.  The chatbot in Phase 3 uses the JSON/JSONL files instead.

Output: neo4j_import.cypher  (configured in config.KG_CYPHER_FILE)

Usage within Neo4j Browser or cypher-shell:
  :source neo4j_import.cypher

Cypher format:
  MERGE  (n:Mission {node_id: 'mission:insat-3d'})
  SET    n.label = 'INSAT-3D', n.orbit_type = 'Geostationary', …

  MATCH (a {node_id: '…'}), (b {node_id: '…'})
  MERGE (a)-[:HAS_PAYLOAD]->(b)
─────────────────────────────────────────────────────────────────────────────
"""

import re
from pathlib import Path
from typing import Any, Dict

import networkx as nx

from config import KG_CYPHER_FILE
from utils.logger import get_logger

log = get_logger(__name__)

# Max property value length (Neo4j string limit is 64 KB, we cap lower)
MAX_PROP_LEN = 2000


def _escape(value: str) -> str:
    """Escape a string for use inside Cypher single-quoted strings."""
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _cypher_props(attrs: Dict[str, Any], exclude: set = None) -> str:
    """
    Build a Cypher property map string from an attributes dict.
    e.g. {label: 'INSAT-3D', orbit_type: 'Geostationary'}
    """
    if exclude is None:
        exclude = set()

    parts = []
    for key, val in attrs.items():
        if key in exclude:
            continue
        if val is None:
            continue
        safe_key = re.sub(r"[^a-zA-Z0-9_]", "_", str(key))
        if isinstance(val, bool):
            parts.append(f"{safe_key}: {str(val).lower()}")
        elif isinstance(val, (int, float)):
            parts.append(f"{safe_key}: {val}")
        else:
            s = str(val)[:MAX_PROP_LEN]
            parts.append(f"{safe_key}: '{_escape(s)}'")

    return "{" + ", ".join(parts) + "}"


class Neo4jExporter:
    """
    Generates a .cypher file for importing the MOSDAC KG into Neo4j.

    Usage:
        exporter = Neo4jExporter()
        exporter.export(G)   # writes to config.KG_CYPHER_FILE
    """

    def __init__(self, output_path: Path = KG_CYPHER_FILE):
        self.output_path = output_path

    def export(self, G: nx.DiGraph) -> int:
        """
        Write Cypher statements to file.
        Returns total number of statements written.
        """
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        total = 0

        with open(self.output_path, "w", encoding="utf-8") as f:

            # ── Header comment ──────────────────────────────────
            f.write("// MOSDAC Knowledge Graph — Neo4j Cypher Import\n")
            f.write("// Generated by Phase 2: Knowledge Graph Construction\n")
            f.write("// Import via: :source neo4j_import.cypher\n\n")

            # ── Constraints (run once to ensure uniqueness) ────
            f.write("// ── Constraints ──────────────────────────────\n")
            node_types = {
                G.nodes[n].get("node_type", "Node")
                for n in G.nodes
            }
            for nt in sorted(node_types):
                safe_nt = re.sub(r"[^a-zA-Z0-9]", "", nt)
                f.write(
                    f"CREATE CONSTRAINT IF NOT EXISTS "
                    f"FOR (n:{safe_nt}) REQUIRE n.node_id IS UNIQUE;\n"
                )
            f.write("\n")

            # ── Node MERGE statements ──────────────────────────
            f.write("// ── Nodes ────────────────────────────────────\n")
            for node_id, attrs in G.nodes(data=True):
                node_type = attrs.get("node_type", "Node")
                safe_nt   = re.sub(r"[^a-zA-Z0-9]", "", node_type)

                # Build property map — exclude 'text' from node props
                # (text goes in a separate full-text index in production)
                prop_map = _cypher_props(
                    attrs,
                    exclude={"node_type"},
                )
                f.write(
                    f"MERGE (n:{safe_nt} {{node_id: '{_escape(node_id)}'}})\n"
                    f"SET n += {prop_map};\n\n"
                )
                total += 1

            # ── Edge MERGE statements ──────────────────────────
            f.write("// ── Relationships ────────────────────────────\n")
            for src, tgt, attrs in G.edges(data=True):
                rel_type = attrs.get("relation_type", "RELATED_TO")
                rel_type = re.sub(r"[^A-Z0-9_]", "_", rel_type.upper())

                # Build edge properties (exclude relation_type itself)
                edge_attrs = {
                    k: v for k, v in attrs.items()
                    if k != "relation_type"
                }
                if edge_attrs:
                    prop_str = " " + _cypher_props(edge_attrs)
                else:
                    prop_str = ""

                f.write(
                    f"MATCH (a {{node_id: '{_escape(src)}'}}), "
                    f"(b {{node_id: '{_escape(tgt)}'}})\n"
                    f"MERGE (a)-[:{rel_type}{prop_str}]->(b);\n\n"
                )
                total += 1

        size_kb = self.output_path.stat().st_size / 1024
        log.info(
            f"Neo4jExporter: {total} statements written to "
            f"{self.output_path.name} ({size_kb:.1f} KB)"
        )
        return total
